name: JRPasd1m23

on:
  workflow_dispatch:
  schedule:
    - cron: "0/30 * * * *"

concurrency:
  group: JRPasd1m23-concurrency
  cancel-in-progress: false

jobs:
  JRPasd1m23:
    runs-on: ubuntu-latest
    environment: JRPasd1m23
    permissions:
      contents: write
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_PUBLISHABLE_KEY: ${{ secrets.SUPABASE_PUBLISHABLE_KEY }}
      ABANDONED_QUEUE_DAYS_TO_CANCEL: ${{ vars.ABANDON_QUEUE_DAYS_TO_CANCEL }}
      ABANDONED_PROCESS_DAYS_TO_CANCEL: ${{ vars.ABANDON_PROCESS_DAYS_TO_CANCEL }}
      PRIO_ACCOUNT_RESET_DAYS: ${{ vars.PRIO_ACCOUNT_RESET_DAYS }}
      NON_PRIO_ACCOUNT_RESET_DAYS: ${{ vars.NON_PRIO_ACCOUNT_RESET_DAYS }}
      ACTIVE_ACCOUNT_ERROR_COUNT: ${{ vars.ACTIVE_ACCOUNT_ERROR_COUNT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO_PATH }}
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          ref: ${{ secrets.PRIVATE_REPO_BRANCH }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: |
          pip install click supabase pytz
      - name: Process
        timeout-minutes: 10
        continue-on-error: true
        run: |
          python jobs.py
